export const RESUME_AUDIO_CONTEXT = 'RESUME_AUDIO_CONTEXT';
export const SET_AUDIO_CONTEXT = 'SET_AUDIO_CONTEXT';
export const SET_GAIN = 'SET_GAIN';
export const SET_GAIN_VALUE = 'SET_GAIN_VALUE';
export const SET_NOW = 'SET_NOW';
export const SET_SOURCE = 'SET_SOURCE';
export const SET_SOURCE_BUFFER = 'SET_SOURCE_BUFFER';
export const SUSPEND_AUDIO_CONTEXT = 'SUSPEND_AUDIO_CONTEXT';
